#!/usr/bin/env python3
"""Writes the widget layouts in app/src/main/res/layout from shared pieces.

Run from android/: python3 tools/gen_layouts.py
App widgets only accept FrameLayout, LinearLayout, TextView and ImageView here,
so every row is spelled out and shown or hidden from code.
"""
import os
import re

OUT = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "res", "layout")
NS = 'xmlns:android="http://schemas.android.com/apk/res/android"'


def tv(id_, text, size, color, family="sans-serif-condensed", bold=False, caps=False, spacing=None, lines=1,
       w="wrap_content", h="wrap_content", extra=""):
    a = {}
    if id_:
        a["android:id"] = f"@+id/{id_}"
    a.update({"android:layout_width": w, "android:layout_height": h, "android:fontFamily": family, "android:text": text,
              "android:textSize": size, "android:textColor": f"@color/{color}"})
    if bold:
        a["android:textStyle"] = "bold"
    if caps:
        a["android:textAllCaps"] = "true"
    if spacing:
        a["android:letterSpacing"] = spacing
    if lines:
        a["android:maxLines"] = str(lines)
        a["android:ellipsize"] = "end"
    for k, v in re.findall(r'(\S+?)="([^"]*)"', extra):
        a[k] = v  # extra settings win over the defaults above
    return "<TextView " + " ".join(f'{k}="{v}"' for k, v in a.items()) + " />"


RES = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "res")


def write(name, body):
    """Writes a layout. Every colour that differs between the looks is set from code, so one layout serves both."""
    head_ = '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/gen_layouts.py -->\n'
    with open(os.path.join(OUT, name), "w", encoding="utf-8") as f:
        f.write(head_ + body.strip() + "\n")


def write_res(folder, name, body):
    with open(os.path.join(RES, folder, name), "w", encoding="utf-8") as f:
        f.write(body.strip() + "\n")


# The widgets, in the app's look ------------------------------------------------------------
# Each widget is a piece of the app: the briefing and the dashboard's top on black like the deck, the moves,
# companies and trends on the directory's light grey, and the licences on the licence colour, as a move's
# page. Colours, type pictures and taps are set from code (Kit and the widgets), in either look; the
# defaults here only show the layout. Rows, tiles and boxes are shared parts.

KIT_FILLS = {
    # swatch and tile fills: the app's page colours, the licence colour a step darker for a licence on its own
    # page, and the black-and-white tones with their one-step neighbours
    "yellow": "#FCED00", "yellowdeep": "#B0A600", "royal": "#263B94", "crimson": "#8B1112", "violet": "#975ACA",
    "sage": "#618C75", "slate": "#7E888B", "paper": "#F2F2F2", "paperstep": "#DADADA", "silver": "#B4B4B4",
    "black": "#000000", "blackstep": "#1F1F1F",
}
KIT_LINED = ["paper", "paperstep", "silver", "black", "blackstep"]
KIT_DARK = {"black", "blackstep", "royal", "crimson"}
KIT_ROWS = {"paper": "#DEDEDE", "night": "#121212", "yellow": "#D1C500", "paperstep": "#DADADA"}
KIT_GROUNDS = {"paper": "#D6D6D6", "yellow": "#FCED00", "tonepaper": "#F2F2F2"}


def write_kit_resources():
    for k, fill in KIT_FILLS.items():
        edge = "#3A3A3A" if k in ("black", "blackstep") else "#1F000000"
        write_res("drawable", f"sw_{k}.xml", f"""<!-- Generated by tools/gen_layouts.py: a move's swatch -->
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">
    <solid android:color="{fill}" />
    <stroke android:width="1dp" android:color="{edge}" />
    <corners android:radius="2dp" />
</shape>""")
        if k in KIT_LINED:
            lines = "light" if k in KIT_DARK else "dark"
            write_res("drawable", f"sw_{k}_lined.xml", f"""<!-- Generated by tools/gen_layouts.py: the second kind of a family, in black and white -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@drawable/sw_{k}" />
    <item android:left="1dp" android:top="1dp" android:right="1dp" android:bottom="1dp"><bitmap android:src="@drawable/hatch_sw_{lines}" android:tileMode="repeat" /></item>
</layer-list>""")
    for k, fill in KIT_ROWS.items():
        write_res("drawable", f"row_{k}.xml", f"""<!-- Generated by tools/gen_layouts.py: a row -->
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">
    <solid android:color="{fill}" />
    <corners android:radius="2dp" />
</shape>""")
    for k, fill in KIT_GROUNDS.items():
        write_res("drawable", f"bg_{k}.xml", f"""<!-- Generated by tools/gen_layouts.py: a widget's ground -->
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">
    <solid android:color="{fill}" />
    <corners android:radius="26dp" />
</shape>""")
    for k, fill in (("black", "#000000"), ("paper", "#F2F2F2"), ("paperstep", "#DADADA")):
        write_res("drawable", f"tile_{k}.xml", f"""<!-- Generated by tools/gen_layouts.py: a regulator's tile -->
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">
    <solid android:color="{fill}" />
    <corners android:radius="3dp" />
</shape>""")
    # The dashboard's black top, rounded at the top as the widget is, for launchers that do not clip to it.
    write_res("drawable", "bg_cover.xml", """<!-- Generated by tools/gen_layouts.py: the dashboard's briefing -->
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">
    <solid android:color="#000000" />
    <corners android:topLeftRadius="26dp" android:topRightRadius="26dp" android:bottomLeftRadius="0dp" android:bottomRightRadius="0dp" />
</shape>""")
    write_res("drawable", "rule_kit.xml", """<!-- Generated by tools/gen_layouts.py -->
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle"><solid android:color="#C9C9C9" /></shape>""")
    write_res("drawable", "ic_kit_refresh.xml", """<!-- Generated by tools/gen_layouts.py: the app's refresh icon, tinted from code -->
<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="24dp" android:height="24dp" android:viewportWidth="24" android:viewportHeight="24">
    <path android:strokeColor="#FFFFFF" android:strokeWidth="1.9" android:strokeLineCap="round" android:strokeLineJoin="round" android:fillColor="#00000000" android:pathData="M19,12a7,7 0,1 1,-2.05 -4.95" />
    <path android:strokeColor="#FFFFFF" android:strokeWidth="1.9" android:strokeLineCap="round" android:strokeLineJoin="round" android:fillColor="#00000000" android:pathData="M19,4.5V8h-3.5" />
</vector>""")
    write_hatch("hatch_sw_dark.png", (0, 0, 0, 0x6B), tile=10, width=3.0)
    write_hatch("hatch_sw_light.png", (255, 255, 255, 0x99), tile=10, width=3.0)


def text(id_, sample, size, color="#000000", family="sans-serif", bold=False, caps=False, lines=1, w="wrap_content", extra=""):
    """Ordinary widget text in the system face: the small text round the app's type pictures."""
    a = {"android:id": f"@+id/{id_}", "android:layout_width": w, "android:layout_height": "wrap_content", "android:fontFamily": family,
         "android:text": sample, "android:textSize": size, "android:textColor": color, "android:includeFontPadding": "false"}
    if bold:
        a["android:textStyle"] = "bold"
    if caps:
        a["android:textAllCaps"] = "true"
        a["android:letterSpacing"] = "0.08"
    if lines:
        a["android:maxLines"] = str(lines)
        a["android:ellipsize"] = "end"
    for k, v in re.findall(r'(\S+?)="([^"]*)"', extra):
        a[k] = v
    return "<TextView " + " ".join(f'{k}="{v}"' for k, v in a.items()) + " />"


def picture(id_, extra=""):
    """A picture drawn from code: a heading, number or name in the app's typeface, or a chart."""
    return f'<ImageView android:id="@+id/{id_}" android:layout_width="wrap_content" android:layout_height="wrap_content" android:importantForAccessibility="no" {extra} />'


def kit_head(sample_colour="#000000"):
    """A directory heading, the app's huge title, with the refresh at the right."""
    return f"""<FrameLayout android:id="@+id/head" android:layout_width="match_parent" android:layout_height="wrap_content"
        android:paddingStart="14dp" android:paddingTop="10dp" android:paddingEnd="2dp">
        {picture("heading")}
        <ImageView android:id="@+id/refresh" android:layout_width="40dp" android:layout_height="40dp" android:layout_gravity="end|top"
            android:padding="11dp" android:src="@drawable/ic_kit_refresh" android:tint="{sample_colour}" android:contentDescription="Check for news now" />
    </FrameLayout>"""


def kit_row(p="", root="row_item"):
    """A move as a row, as the app lists them: its swatch, the title, what and who, and the day."""
    return f"""<FrameLayout android:id="@+id/{p}{root}" android:layout_width="match_parent" android:layout_height="wrap_content" android:paddingBottom="2dp">
        <LinearLayout android:id="@+id/{p}row" android:layout_width="match_parent" android:layout_height="wrap_content" android:background="@drawable/row_paper"
            android:gravity="center_vertical" android:orientation="horizontal" android:paddingStart="8dp" android:paddingTop="9dp" android:paddingEnd="10dp" android:paddingBottom="9dp">
            <FrameLayout android:id="@+id/{p}sw" android:layout_width="36dp" android:layout_height="36dp" android:background="@drawable/sw_royal">
                <ImageView android:id="@+id/{p}sw_glyph" android:layout_width="10dp" android:layout_height="10dp" android:layout_gravity="center"
                    android:importantForAccessibility="no" android:src="@drawable/g_dia" />
            </FrameLayout>
            <LinearLayout android:layout_width="0dp" android:layout_height="wrap_content" android:layout_weight="1" android:layout_marginStart="12dp" android:orientation="vertical">
                {text(p + "title", "NCUA proposes stablecoin data fields for credit union call reports", "14sp", bold=True, lines=2, w="match_parent", extra='android:lineHeight="18sp"')}
                {text(p + "meta", "Regulation · NCUA · North America", "11.5sp", "#9A9A9A", family="sans-serif-medium", w="match_parent", extra='android:layout_marginTop="3dp"')}
            </LinearLayout>
            {text(p + "date", "9 Oct", "13sp", "#9A9A9A", family="sans-serif-medium", extra='android:layout_marginStart="8dp"')}
        </LinearLayout>
    </FrameLayout>"""


def kit_tile(p):
    """One of the newest moves as the app's tile: its name on its colour, and the figure in a black block."""
    return f"""<LinearLayout android:id="@+id/{p}" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1"
            android:background="@drawable/card_royal" android:orientation="vertical" android:padding="8dp">
            {picture(p + "_name")}
            <FrameLayout android:layout_width="match_parent" android:layout_height="0dp" android:layout_weight="1" />
            <FrameLayout android:id="@+id/{p}_panel" android:layout_width="match_parent" android:layout_height="wrap_content" android:background="@drawable/panel_black" android:padding="6dp">
                {picture(p + "_fig")}
            </FrameLayout>
        </LinearLayout>"""


def kit_regtile(p):
    """A regulator as the app's tile: how many moves, huge, then its name and where."""
    return f"""<LinearLayout android:id="@+id/{p}" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1"
            android:background="@drawable/tile_black" android:orientation="vertical" android:padding="8dp">
            {picture(p + "_n")}
            <FrameLayout android:layout_width="match_parent" android:layout_height="0dp" android:layout_weight="1" />
            {picture(p + "_name")}
            {text(p + "_where", "United States", "10.5sp", "#99FFFFFF", family="sans-serif-medium", w="match_parent", extra='android:layout_marginTop="2dp"')}
        </LinearLayout>"""


def kit_box(p, height, initials_extra=""):
    """A company as the app's Watching box: its name, what and where, its initials huge, and its latest move."""
    return f"""<FrameLayout android:id="@+id/{p}box" android:layout_width="match_parent" android:layout_height="{height}" android:background="@drawable/card_royal" android:padding="10dp">
            <LinearLayout android:layout_width="match_parent" android:layout_height="wrap_content" android:orientation="vertical">
                {text(p + "box_name", "Ripple", "13sp", bold=True, lines=2, w="match_parent")}
                {text(p + "box_sub", "Settlement rails · United States", "10.5sp", "#8C000000", family="sans-serif-medium", w="match_parent", extra='android:layout_marginTop="2dp"')}
            </LinearLayout>
            <LinearLayout android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_gravity="bottom" android:orientation="vertical">
                {picture(p + "box_initials", initials_extra)}
                <LinearLayout android:id="@+id/{p}box_latest_row" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="4dp"
                    android:gravity="center_vertical" android:orientation="horizontal">
                    <ImageView android:id="@+id/{p}box_glyph" android:layout_width="7dp" android:layout_height="7dp" android:importantForAccessibility="no" android:src="@drawable/g_dia" />
                    {text(p + "box_latest", "Funding · 8 Oct", "9.5sp", "#8C000000", bold=True, caps=True, w="0dp", extra='android:layout_weight="1" android:layout_marginStart="5dp"')}
                </LinearLayout>
            </LinearLayout>
        </FrameLayout>"""


def label(id_, sample, color="#000000", extra=""):
    """A section's small capitals, as the app's month headers."""
    return text(id_, sample, "10.5sp", color, bold=True, caps=True, w="match_parent",
                extra='android:paddingStart="14dp" android:paddingEnd="14dp" ' + extra)


LIST = ('android:divider="@null" android:dividerHeight="0dp" android:scrollbars="none" android:listSelector="@android:color/transparent" '
        'android:cacheColorHint="#00000000" android:clipToPadding="false"')

# 1. Daily briefing, 4 x 2 and taller: on black, as the app's home ------------------------------
write("widget_brief.xml", f"""
<FrameLayout {NS} android:id="@android:id/background" android:layout_width="match_parent" android:layout_height="match_parent"
    android:background="@drawable/bg_deck" android:clipToOutline="true">
    <LinearLayout android:layout_width="match_parent" android:layout_height="match_parent" android:orientation="vertical">
        <FrameLayout android:id="@+id/top" android:layout_width="match_parent" android:layout_height="44dp">
            <ImageView android:id="@+id/topline" android:layout_width="match_parent" android:layout_height="match_parent" android:scaleType="matrix" android:importantForAccessibility="no" />
            <ImageView android:id="@+id/refresh" android:layout_width="40dp" android:layout_height="44dp" android:layout_gravity="end" android:padding="12dp"
                android:src="@drawable/ic_kit_refresh" android:tint="#8CFFFFFF" android:contentDescription="Check for news now" />
        </FrameLayout>
        <LinearLayout android:id="@+id/hero" android:layout_width="match_parent" android:layout_height="wrap_content" android:orientation="horizontal"
            android:paddingStart="18dp" android:paddingEnd="18dp">
            <LinearLayout android:id="@+id/count_col" android:layout_width="wrap_content" android:layout_height="wrap_content" android:orientation="vertical">
                {picture("count")}
                {text("count_label", "Moves in 7 days", "10sp", "#BFFFFFFF", bold=True, caps=True, lines=2, extra='android:layout_marginTop="2dp" android:lineHeight="12sp"')}
                {text("dates", "4–10 Oct", "10sp", "#80FFFFFF", bold=True, caps=True, extra='android:layout_marginTop="3dp"')}
            </LinearLayout>
            {text("headline", "Samsung Wallet will add USDC transfers for US Galaxy users as Anchorage bought Routable.", "13.5sp", "#FFFFFF", lines=6, w="0dp",
                  extra='android:layout_weight="1" android:layout_marginStart="16dp" android:layout_marginTop="4dp" android:lineHeight="18sp"')}
        </LinearLayout>
        {picture("mix", 'android:layout_marginStart="18dp" android:layout_marginTop="14dp"')}
        {label("latest_label", "Latest", "#80FFFFFF", 'android:layout_marginTop="16dp" android:paddingStart="18dp"')}
        <ListView android:id="@+id/list" android:layout_width="match_parent" android:layout_height="0dp" android:layout_weight="1" android:layout_marginTop="6dp"
            android:paddingStart="10dp" android:paddingEnd="10dp" android:paddingBottom="10dp" {LIST} />
    </LinearLayout>
</FrameLayout>""")

# 2. Moves, 4 x 4: the app's Moves screen ----------------------------------------------------------
write("widget_moves.xml", f"""
<FrameLayout {NS} android:id="@android:id/background" android:layout_width="match_parent" android:layout_height="match_parent"
    android:background="@drawable/bg_paper" android:clipToOutline="true">
    <LinearLayout android:layout_width="match_parent" android:layout_height="match_parent" android:orientation="vertical">
        {kit_head()}
        <LinearLayout android:id="@+id/tiles" android:layout_width="match_parent" android:layout_height="124dp" android:layout_marginTop="6dp"
            android:orientation="horizontal" android:paddingStart="12dp" android:paddingEnd="12dp">
            {kit_tile("t1")}
            <FrameLayout android:layout_width="7dp" android:layout_height="match_parent" />
            {kit_tile("t2")}
            <FrameLayout android:layout_width="7dp" android:layout_height="match_parent" />
            {kit_tile("t3")}
        </LinearLayout>
        {label("list_label", "Earlier", extra='android:layout_marginTop="16dp"')}
        <ListView android:id="@+id/list" android:layout_width="match_parent" android:layout_height="0dp" android:layout_weight="1" android:layout_marginTop="6dp"
            android:paddingStart="6dp" android:paddingEnd="6dp" android:paddingBottom="6dp" {LIST} />
    </LinearLayout>
</FrameLayout>""")

# 3. Companies, 4 x 4: the app's Watching boxes ----------------------------------------------------
write("widget_companies.xml", f"""
<FrameLayout {NS} android:id="@android:id/background" android:layout_width="match_parent" android:layout_height="match_parent"
    android:background="@drawable/bg_paper" android:clipToOutline="true">
    <LinearLayout android:layout_width="match_parent" android:layout_height="match_parent" android:orientation="vertical">
        {kit_head()}
        {label("sub", "Most active · 30 days", "#9A9A9A", 'android:layout_marginTop="2dp"')}
        <GridView android:id="@+id/grid" android:layout_width="match_parent" android:layout_height="0dp" android:layout_weight="1" android:layout_marginTop="8dp"
            android:numColumns="2" android:stretchMode="columnWidth" android:paddingStart="9dp" android:paddingEnd="9dp" android:paddingBottom="9dp"
            android:scrollbars="none" android:listSelector="@android:color/transparent" android:clipToPadding="false" />
    </LinearLayout>
</FrameLayout>""")

# 4. Licences, 4 x 4: a licence's page, in the licence colour ---------------------------------------
write("widget_licences.xml", f"""
<FrameLayout {NS} android:id="@android:id/background" android:layout_width="match_parent" android:layout_height="match_parent"
    android:background="@drawable/bg_yellow" android:clipToOutline="true">
    <LinearLayout android:layout_width="match_parent" android:layout_height="match_parent" android:orientation="vertical">
        {kit_head()}
        <LinearLayout android:id="@+id/tiles" android:layout_width="match_parent" android:layout_height="112dp" android:layout_marginTop="6dp"
            android:orientation="horizontal" android:paddingStart="12dp" android:paddingEnd="12dp">
            {kit_regtile("g1")}
            <FrameLayout android:layout_width="7dp" android:layout_height="match_parent" />
            {kit_regtile("g2")}
            <FrameLayout android:layout_width="7dp" android:layout_height="match_parent" />
            {kit_regtile("g3")}
        </LinearLayout>
        {label("list_label", "Latest licences and rules", extra='android:layout_marginTop="16dp"')}
        <ListView android:id="@+id/list" android:layout_width="match_parent" android:layout_height="0dp" android:layout_weight="1" android:layout_marginTop="6dp"
            android:paddingStart="6dp" android:paddingEnd="6dp" android:paddingBottom="6dp" {LIST} />
    </LinearLayout>
</FrameLayout>""")


def CHART(extra=""):
    """The month chart: whatever room is left, measured from code and drawn to fit it exactly."""
    return ('<ImageView android:id="@+id/chart" android:layout_width="match_parent" android:layout_height="0dp" android:layout_weight="1" '
            'android:layout_marginStart="14dp" android:layout_marginEnd="14dp" android:scaleType="fitCenter" ' + extra + ' />')


def kit_stat(i):
    sep = "" if i == 1 else '<FrameLayout android:layout_width="1dp" android:layout_height="match_parent" android:background="@drawable/rule_kit" />'
    return f"""{sep}
            <LinearLayout android:layout_width="0dp" android:layout_height="wrap_content" android:layout_weight="1" android:orientation="vertical"
                android:paddingStart="{0 if i == 1 else 9}dp">
                {picture(f"s{i}_n")}
                {text(f"s{i}_label", "Licences", "11sp", "#9A9A9A", family="sans-serif-medium", w="match_parent", extra='android:layout_marginTop="3dp"')}
            </LinearLayout>"""


# 5. Trends, 4 x 3: the app's Trends screen --------------------------------------------------------
write("widget_trends.xml", f"""
<FrameLayout {NS} android:id="@android:id/background" android:layout_width="match_parent" android:layout_height="match_parent"
    android:background="@drawable/bg_paper" android:clipToOutline="true">
    <LinearLayout android:layout_width="match_parent" android:layout_height="match_parent" android:orientation="vertical">
        {kit_head()}
        {picture("since", 'android:layout_marginStart="14dp" android:layout_marginTop="2dp"')}
        <LinearLayout android:id="@+id/stats" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="12dp"
            android:orientation="horizontal" android:paddingStart="14dp" android:paddingEnd="14dp">
            {kit_stat(1)}{kit_stat(2)}{kit_stat(3)}{kit_stat(4)}
        </LinearLayout>
        {CHART('android:layout_marginTop="14dp"')}
        {picture("legend", 'android:layout_marginStart="14dp" android:layout_marginTop="6dp" android:layout_marginBottom="12dp"')}
    </LinearLayout>
</FrameLayout>""")


def kit_minibox(i):
    return f"""<FrameLayout android:id="@+id/c{i}" android:layout_width="0dp" android:layout_height="match_parent" android:layout_weight="1">
            {kit_box(f"c{i}_", "match_parent")}
        </FrameLayout>"""


# 6. Dashboard, 4 x 5: the briefing on black, then the week on light grey ---------------------------
write("widget_dashboard.xml", f"""
<FrameLayout {NS} android:id="@android:id/background" android:layout_width="match_parent" android:layout_height="match_parent"
    android:background="@drawable/bg_paper" android:clipToOutline="true">
    <LinearLayout android:layout_width="match_parent" android:layout_height="match_parent" android:orientation="vertical">
        <LinearLayout android:id="@+id/cover" android:layout_width="match_parent" android:layout_height="wrap_content" android:background="@drawable/bg_cover"
            android:orientation="vertical" android:paddingBottom="16dp">
            <FrameLayout android:id="@+id/top" android:layout_width="match_parent" android:layout_height="44dp">
                <ImageView android:id="@+id/topline" android:layout_width="match_parent" android:layout_height="match_parent" android:scaleType="matrix" android:importantForAccessibility="no" />
                <ImageView android:id="@+id/refresh" android:layout_width="40dp" android:layout_height="44dp" android:layout_gravity="end" android:padding="12dp"
                    android:src="@drawable/ic_kit_refresh" android:tint="#8CFFFFFF" android:contentDescription="Check for news now" />
            </FrameLayout>
            <LinearLayout android:id="@+id/hero" android:layout_width="match_parent" android:layout_height="wrap_content" android:orientation="horizontal"
                android:paddingStart="18dp" android:paddingEnd="18dp">
                <LinearLayout android:id="@+id/count_col" android:layout_width="wrap_content" android:layout_height="wrap_content" android:orientation="vertical">
                    {picture("count")}
                    {text("count_label", "Moves in 7 days", "10sp", "#BFFFFFFF", bold=True, caps=True, lines=2, extra='android:layout_marginTop="2dp" android:lineHeight="12sp"')}
                </LinearLayout>
                {text("headline", "Samsung Wallet will add USDC transfers for US Galaxy users.", "13sp", "#FFFFFF", lines=4, w="0dp",
                      extra='android:layout_weight="1" android:layout_marginStart="16dp" android:layout_marginTop="4dp" android:lineHeight="17sp"')}
            </LinearLayout>
            {picture("mix", 'android:layout_marginStart="18dp" android:layout_marginTop="12dp"')}
        </LinearLayout>
        {label("latest_label", "Latest", extra='android:layout_marginTop="14dp"')}
        <LinearLayout android:id="@+id/rows" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="6dp"
            android:orientation="vertical" android:paddingStart="6dp" android:paddingEnd="6dp">
            {kit_row("r1_")}
            {kit_row("r2_")}
            {kit_row("r3_")}
        </LinearLayout>
        {label("co_label", "Most active companies", extra='android:layout_marginTop="12dp"')}
        <LinearLayout android:id="@+id/boxes" android:layout_width="match_parent" android:layout_height="96dp" android:layout_marginTop="6dp"
            android:orientation="horizontal" android:paddingStart="12dp" android:paddingEnd="12dp">
            {kit_minibox(1)}
            <FrameLayout android:layout_width="7dp" android:layout_height="match_parent" />
            {kit_minibox(2)}
            <FrameLayout android:layout_width="7dp" android:layout_height="match_parent" />
            {kit_minibox(3)}
        </LinearLayout>
        {label("reg_label", "Busiest regulators", extra='android:layout_marginTop="12dp"')}
        <LinearLayout android:id="@+id/tiles" android:layout_width="match_parent" android:layout_height="84dp" android:layout_marginTop="6dp"
            android:orientation="horizontal" android:paddingStart="12dp" android:paddingEnd="12dp">
            {kit_regtile("g1")}
            <FrameLayout android:layout_width="7dp" android:layout_height="match_parent" />
            {kit_regtile("g2")}
            <FrameLayout android:layout_width="7dp" android:layout_height="match_parent" />
            {kit_regtile("g3")}
        </LinearLayout>
        {CHART('android:layout_marginTop="12dp" android:layout_marginBottom="12dp"')}
    </LinearLayout>
</FrameLayout>""")

# The parts lists are made of: a move's row (the briefing, moves and licences) and a company's box.
write("widget_row.xml", f"""
{kit_row().replace('<FrameLayout android:id="@+id/row_item"', f'<FrameLayout {NS} android:id="@+id/row_item"', 1)}""")
write("widget_month.xml", f"""
<LinearLayout {NS} android:id="@+id/month_item" android:layout_width="match_parent" android:layout_height="wrap_content" android:orientation="horizontal"
    android:paddingStart="8dp" android:paddingTop="12dp" android:paddingEnd="8dp" android:paddingBottom="7dp">
    {text("month_label", "October 2026", "10.5sp", bold=True, caps=True, w="0dp", extra='android:layout_weight="1"')}
    {text("month_n", "24", "10.5sp", bold=True, caps=True)}
</LinearLayout>""")
write("widget_box.xml", f"""
<FrameLayout {NS} android:id="@+id/box_item" android:layout_width="match_parent" android:layout_height="wrap_content" android:padding="3dp">
    {kit_box("", "128dp")}
</FrameLayout>""")


# 7. Carousel, 4 x 4: the app's cards as a list ----------------------------------------------
# A list that scrolls like any list, of the app's cards made shorter: the name, then the black block with
# the kind, the figure, the title and the date. The names and figures are set in the app's typeface, drawn
# from code as small pictures and tinted here; everything else is ordinary widget views. Colours, sizes
# and taps are set from code (CarouselWidget), in either look; the defaults here only show the layout.

DECK_COLOURS = {
    # name: (fill, stroke): the app's page colours in colour, and its three tones in black and white
    "yellow": ("#FCED00", None), "royal": ("#263B94", None), "crimson": ("#8B1112", None),
    "violet": ("#975ACA", None), "sage": ("#618C75", None), "slate": ("#7E888B", None),
    "paper": ("#F2F2F2", "#000000"), "silver": ("#B4B4B4", "#000000"), "black": ("#000000", "#3A3A3A"),
}


def write_deck_resources():
    write_res("values", "colors_deck.xml", '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/gen_layouts.py: the carousel widget -->\n<resources>\n'
              + "".join(f'    <color name="deck_{k}">{v[0]}</color>\n' for k, v in DECK_COLOURS.items())
              + '    <color name="deck_faint">#80FFFFFF</color>\n</resources>')
    for k, (fill, stroke) in DECK_COLOURS.items():
        st = f'\n    <stroke android:width="1dp" android:color="{stroke}" />' if stroke else ""
        write_res("drawable", f"card_{k}.xml", f"""<!-- Generated by tools/gen_layouts.py -->
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">
    <solid android:color="{fill}" />{st}
    <corners android:radius="3dp" />
</shape>""")
    for k, fill in (("black", "#000000"), ("paper", "#F2F2F2")):
        write_res("drawable", f"panel_{k}.xml", f"""<!-- Generated by tools/gen_layouts.py -->
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">
    <solid android:color="{fill}" />
    <corners android:radius="2dp" />
</shape>""")
        # The second kind of each family in black and white: fine diagonal lines over the block.
        write_res("drawable", f"panel_{k}_lined.xml", f"""<!-- Generated by tools/gen_layouts.py -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@drawable/panel_{k}" />
    <item><bitmap android:src="@drawable/hatch_on_{k}" android:tileMode="repeat" /></item>
</layer-list>""")
    write_res("drawable", "bg_deck.xml", """<!-- Generated by tools/gen_layouts.py -->
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">
    <solid android:color="#000000" />
    <corners android:radius="26dp" />
</shape>""")
    # The app's deck controls (Icons in ui/Icons.kt), white at 80%.
    for name, path in (("up", "M6,14.5 L12,8.5 L18,14.5"), ("down", "M6,9.5 L12,15.5 L18,9.5")):
        write_res("drawable", f"ic_deck_{name}.xml", f"""<!-- Generated by tools/gen_layouts.py -->
<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="24dp" android:height="24dp" android:viewportWidth="24" android:viewportHeight="24">
    <path android:strokeColor="#CCFFFFFF" android:strokeWidth="2" android:strokeLineCap="round" android:strokeLineJoin="round" android:fillColor="#00000000" android:pathData="{path}" />
</vector>""")
    write_res("drawable", "ic_deck_grid.xml", """<!-- Generated by tools/gen_layouts.py -->
<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="24dp" android:height="24dp" android:viewportWidth="24" android:viewportHeight="24">
    <path android:strokeColor="#CCFFFFFF" android:strokeWidth="1.6" android:strokeLineCap="round" android:strokeLineJoin="round" android:fillColor="#00000000" android:pathData="M5,5h5.5v5.5H5zM13.5,5H19v5.5h-5.5zM5,13.5h5.5V19H5zM13.5,13.5H19V19h-5.5z" />
</vector>""")
    # Hollow glyphs mark the second kind of each family in black and white; tinted from code.
    for name, path in (("dia", "M5,1.3 L8.7,5 L5,8.7 L1.3,5 Z"), ("sq", "M1.9,1.9 H8.1 V8.1 H1.9 Z"), ("dot", "M1.7,5 a3.3,3.3 0 1,0 6.6,0 a3.3,3.3 0 1,0 -6.6,0")):
        write_res("drawable", f"g_{name}_o.xml", f"""<!-- Generated by tools/gen_layouts.py -->
<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="8dp" android:height="8dp" android:viewportWidth="10" android:viewportHeight="10">
    <path android:strokeColor="#FFFFFF" android:strokeWidth="1.6" android:fillColor="#00000000" android:pathData="{path}" />
</vector>""")
    write_hatch("hatch_on_black.png", (255, 255, 255, 0x2E))
    write_hatch("hatch_on_paper.png", (0, 0, 0, 0x1F))


def write_hatch(name, rgba, tile=18, width=3.0):
    """A seamless tile of one diagonal line (x + y = 0 mod tile), anti-aliased, as a plain PNG."""
    import struct
    import zlib
    r, g, b, a = rgba
    rows = []
    for y in range(tile):
        row = bytearray([0])
        for x in range(tile):
            v = (x + 0.5 + y + 0.5) % tile
            d = min(v, tile - v) / 2 ** 0.5  # distance to the nearest line, in pixels
            cover = max(0.0, min(1.0, width / 2 + 0.5 - d))
            row += bytes([r, g, b, int(round(a * cover))])
        rows.append(bytes(row))
    raw = zlib.compress(b"".join(rows), 9)

    def chunk(t, data):
        return struct.pack(">I", len(data)) + t + data + struct.pack(">I", zlib.crc32(t + data) & 0xFFFFFFFF)
    png = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", tile, tile, 8, 6, 0, 0, 0)) + chunk(b"IDAT", raw) + chunk(b"IEND", b"")
    os.makedirs(os.path.join(RES, "drawable-nodpi"), exist_ok=True)
    with open(os.path.join(RES, "drawable-nodpi", name), "wb") as f:
        f.write(png)


def control(id_, src, desc):
    return (f'<ImageView android:id="@+id/{id_}" android:layout_width="34dp" android:layout_height="34dp" android:padding="8dp" '
            f'android:src="@drawable/{src}" android:contentDescription="{desc}" />')


def caps(id_, text, color, extra=""):
    """The app's small capitals (Type.Caps): bold, 11sp, spaced 0.08em."""
    return tv(id_, text, "11sp", color, family="sans-serif", bold=True, caps=True, spacing="0.08",
              extra='android:includeFontPadding="false" ' + extra)


# The frame: the app's top line (a picture), the list of cards under it, and the app's up, grid and down
# at the bottom left. The list starts 14dp under the top line, as the app's first card does, and the
# cards slide under the top line as it scrolls.
write("widget_carousel.xml", f"""
<FrameLayout {NS} android:id="@android:id/background" android:layout_width="match_parent" android:layout_height="match_parent"
    android:background="@drawable/bg_deck" android:clipToOutline="true">
    <ListView android:id="@+id/list" android:layout_width="match_parent" android:layout_height="match_parent" android:layout_marginTop="44dp"
        android:paddingTop="14dp" android:paddingBottom="6dp" android:clipToPadding="false" android:divider="@null" android:dividerHeight="0dp"
        android:scrollbars="none" android:listSelector="@android:color/transparent" android:cacheColorHint="#00000000" />
    <LinearLayout android:id="@+id/empty" android:layout_width="match_parent" android:layout_height="match_parent" android:layout_marginTop="44dp"
        android:orientation="vertical" android:paddingStart="48dp" android:paddingTop="14dp" android:paddingEnd="48dp">
        {tv("empty_text", "Loading the latest moves…", "15sp", "white", family="sans-serif")}
    </LinearLayout>
    <FrameLayout android:id="@+id/controls" android:layout_width="match_parent" android:layout_height="match_parent">
        <LinearLayout android:id="@+id/cluster" android:layout_width="wrap_content" android:layout_height="wrap_content" android:layout_gravity="bottom|start"
            android:layout_marginStart="10dp" android:layout_marginBottom="18dp" android:orientation="vertical">
            {control("up", "ic_deck_up", "Scroll up a card")}
            {control("grid", "ic_deck_grid", "Open the lists in the app")}
            {control("down", "ic_deck_down", "Scroll down a card")}
        </LinearLayout>
    </FrameLayout>
    <FrameLayout android:id="@+id/top" android:layout_width="match_parent" android:layout_height="44dp" android:background="#000000">
        <ImageView android:id="@+id/topline" android:layout_width="match_parent" android:layout_height="match_parent" android:scaleType="matrix" />
    </FrameLayout>
</FrameLayout>""")


# One card of the list: the app's card, shorter. The name and figure are pictures in the app's typeface;
# the gap between the kind and the figure is all that is left of the app's tall black block.
write("widget_carousel_card.xml", f"""
<FrameLayout {NS} android:id="@+id/item" android:layout_width="match_parent" android:layout_height="wrap_content" android:paddingBottom="8dp">
    <LinearLayout android:id="@+id/card" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginStart="48dp"
        android:layout_marginEnd="48dp" android:background="@drawable/card_royal" android:orientation="vertical" android:padding="10dp">
        <ImageView android:id="@+id/name" android:layout_width="wrap_content" android:layout_height="wrap_content" android:importantForAccessibility="no" />
        <LinearLayout android:id="@+id/panel" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="10dp"
            android:background="@drawable/panel_black" android:orientation="vertical" android:padding="12dp">
            <LinearLayout android:layout_width="match_parent" android:layout_height="wrap_content" android:gravity="center_vertical" android:orientation="horizontal">
                <ImageView android:id="@+id/glyph" android:layout_width="8dp" android:layout_height="8dp" android:importantForAccessibility="no" android:src="@drawable/g_dia" android:tint="@color/deck_royal" />
                {caps("label", "Regulation", "deck_royal", 'android:layout_width="0dp" android:layout_weight="1" android:layout_marginStart="6dp"')}
            </LinearLayout>
            <ImageView android:id="@+id/figure" android:layout_width="wrap_content" android:layout_height="wrap_content" android:layout_marginTop="12dp" android:importantForAccessibility="no" />
            {tv("title", "NCUA proposes stablecoin data fields for credit union call reports", "13sp", "white", family="sans-serif-medium", lines=2, w="match_parent",
                extra='android:layout_marginTop="8dp" android:includeFontPadding="false" android:lineHeight="15sp"')}
            {caps("date", "9 Oct 2026", "deck_faint", 'android:layout_marginTop="6dp"')}
        </LinearLayout>
    </LinearLayout>
</FrameLayout>""")

# Shown for a moment while a card loads on phones before Android 12, where the cards come one by one.
write("widget_carousel_loading.xml", f"""
<FrameLayout {NS} android:layout_width="match_parent" android:layout_height="240dp" android:background="#000000" />""")


write_deck_resources()
write_kit_resources()
print("layouts written to", os.path.normpath(OUT))
